project:
  type: website

website:
  title: "Blog_Shao_Caoyu"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/etc5523-2022
format:
  html:
    toc: true
    toc-depth: 2
    theme: cosmo
    css: styles.css



theme:
  light: flatly
  dark: darkly
