project:
  type: website


website:
  title: "Caoyu Â· Analytics Notes"
  site-url: https://github.com/ETC5523-2025/assignment-3-creating-a-blog-shaocaoyu-01
  navbar:
    background: yellow
    right:
       - about.qmd
       - icon: github
         href: https://github.com/shaocaoyu-01
         aria-label: GitHub

format:
  html:
    css: styles.css
    theme: flatly
