project:
  type: website


website:
  title: "Samuel Shao Â· Analytics Notes"
  navbar:
    background: yellow
    right:
       - about.qmd
       - icon: github
         href: https://github.com/shaocaoyu-01
         aria-label: GitHub

format:
  html:
    css: styles.css
    theme:
      cosmo
