project:
  type: website
  output-dir: docs


website:
  title: "Caoyu Shao"
  navbar:
    left:
      - text: Home
        href: about.qmd
      - text: Blog
        href: index.qmd
      - text: CV
        href: CV.pdf
    right:
      - icon: github
        href: https://github.com/shaocaoyu-01
      - icon: linkedin
        href: https://www.linkedin.com/in/samuel-shao0058

format:
  html:
    theme: cosmo
    css: styles.css
